// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofeirlpnkavnkgjityjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mZWlybHBua2F2bmtnaml0eWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTcwOTQ4MDgsImV4cCI6MjAzMjY3MDgwOH0.vO_xh9XHewoBDYEtSuEJNYJyse3RKeyFpyTuXdAXkp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);